MACRO NEWLINE
    MOV AH,02H
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H
    ENDM
.MODEL SMALL
.STACK 64
.DATA DB
MAXLEN DB 255
ACTLEN DB ? 
STR DB 'THE NUMBER OF WORDS IS: ','$'
INPUT DB 255 DUP('$')
.CODE 
MAIN PROC FAR
    MOV AX, @DATA
    MOV DS,AX
    MOV AH,0AH
    LEA DX, INPUT
    INT 21H   
    ;MOV CL,INPUT
    LEA SI,ACTLEN
    MOV BL,01H
    ;LOOP1: CMP [SI],32 
    ;JE BODY
    ;JMP LOOP2
    ;BODY: INC BL
    ;LOOP2: INC SI
    ;LOOP LOOP1
     NEWLINE 
    MOV AH,09H
    LEA DX,ACTLEN
    INT 21H
    ;INT 21H    
    ;ADD BL,48
    ;MOV AH,02H
    ;MOV DL,BL
    ;INT 21H    
    MOV AX,4C00H
    INT 21H
    MAIN ENDP
    END MAIN